### PR TITLE
fix: create http client on every request

### LINKED ISSUE #86: http requests on Android override byte data
When using multiple Rive components with the url param, each with different urls, the same animation will place in each component. It appears that we are creating a single instance of the HttpClient and the multiple requests override the resulting byte data.

### PR DESCRIPTION
**Pull request by avivian**
Fixes #86. 

I'm not sure if this is the correct way but it fixes the issue on my example.

### CODE REVIEW

File: android/src/main/java/com/rivereactnative/RiveReactNativeView.kt [hunk 1]
```diff
@@ -271,6 +270,7 @@ class RiveReactNativeView(private val context: ThemedReactContext) : FrameLayout
   }
 
   private fun setUrlRiveResource(url: String, autoplay: Boolean = riveAnimationView.autoplay) {
+    val httpClient = HttpClient()
```
Comment (mjohnsullivan) [inline android/src/main/java/com/rivereactnative/RiveReactNativeView.kt:273]: We've got a http loader in the Android runtime; seems a shame to have this implemented twice in Kotlin.

We didn't use the ViewModel stuff as that's tied to lifecycle and you don't get lifecycle events in views (fragments and activities only). Runtime is using Volley to makes things simple and straightforward. (https://github.com/rive-app/rive-android/blob/master/kotlin/src/main/java/app/rive/runtime/kotlin/RiveAnimationView.kt#L164).

I wonder if there's a way to get RN to call down to what's happening in the Android runtime to save on duping code? Happy to help on the Android side if we need to abstract things out a bit.
